### ISSUE TITLE
No gpu on open shift

### ISSUE THREAD

**Issue by DaBeIDS** [os-climate/corporate_data_extraction#9]
Dear all,
we currently work on the following cluster on open shift:
![image](https://github.com/os-climate/corporate_data_extraction/assets/90916810/fd9e887f-7959-4351-a22d-4c7e4893f309)

And now i saw that there is no gpu attached to the deployment:

![image](https://github.com/os-climate/corporate_data_extraction/assets/90916810/5148a6dc-6758-43bb-9325-9756f13df007)

What is the best way to get a gpu attached here? Is there a way to turn it off and on whenever we use it and not all the time?

Best regards,
David

**Comment by redmikhail** [comment]
@DaBeIDS As per our email communication :+1:  not all nodes in our cluster have GPUs to keep expenses down . We have "labeled" and "tainted" nodes with gpu to allow only workload that uses gpu to be scheduled to these nodes. To make sure that workload  can be deployed to gpu enabled nodes please update corresponding `deployment` manifests with following tolerations and selectors: 

- tolerations: 
``` 
spec:
......
  template:
    metadata:
    ....
    spec:
    ........
      initContainers:
      ....
      containers:
      ....
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
        - key: odh/notebook
          value: 'true'
          effect: NoSchedule
```
- affinity or nodeselector:
```
spec:
.....
  template:
  ......
    spec:
      nodeSelector:
        nvidia.com/gpu.present: 'true'
  ......
```
Please let me know if you have any questions
